name: "Test"

on: [workflow_dispatch]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Test build
        uses: home-assistant/builder@2024.08.2
        with:
          args: |
            --test \
            --repository https://github.com/haflandy/addon-wireguard-client \
            --target wireguard_client \
            --branch main \
            --all \
            --docker-hub haflandy \
            --docker-user ${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password ${{ secrets.DOCKERHUB_TOKEN }}
